#version 450
#extension GL_EXT_shader_image_load_formatted : require
#extension GL_EXT_nonuniform_qualifier : enable

//size of a workgroup for compute
layout (local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform sampler2D textures[];
layout(set = 1, binding = 1) uniform sampler2D imageBuffers[];
layout(rgba16f, set = 1, binding = 0) uniform image2D image[];


layout(push_constant) uniform Push 
{
  int frameIndex;
  int width;
  int height;
} push;


void main()
{
  ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 size = imageSize(image[nonuniformEXT(1 + push.frameIndex)]);

  if(texelCoord.x < size.x && texelCoord.y < size.y)
  {
    vec4 color = vec4(1.0);
    //color = texture(imageBuffers[nonuniformEXT(1 + push.frameIndex)], texelCoord);

    imageStore(image[nonuniformEXT(0 + push.frameIndex)], texelCoord, color);
  }
}
